// Resilience scores, 0-10 each. Higher = more resilient on that dimension.
// iso    = isolation / border controllability (chokepoints, island status, remoteness)
// food   = domestic calorie self-sufficiency without imported inputs
// energy = electricity + fuel self-sufficiency; hydro/geo/nuclear share; refining capacity
// gov    = state capacity, political stability, rule of law under stress
// target = LOW strategic value (10 = nobody's target; 0 = first on every list)
// dens   = dispersal (10 = very low population density)
// clim   = survivability without industrial inputs (heat, grow food, get water)
// south  = southern hemisphere (nuclear winter / fallout advantage)
// note   = the single most important caveat or asset

module.exports = {
  554: { n:"New Zealand",   iso:10, food:10, energy:7,  gov:9,  target:9,  dens:9,  clim:9, south:1, note:"Feeds ~5x its population and 85% renewable power — but imports 100% of liquid fuel and closed its only refinery in 2022. No diesel, no farm machinery." },
  36:  { n:"Australia",     iso:9,  food:10, energy:8,  gov:9,  target:6,  dens:10, clim:5, south:1, note:"Enormous food surplus and space. Pine Gap and the US alliance make it a target; the habitable fraction is a coastal ribbon." },
  858: { n:"Uruguay",       iso:6,  food:10, energy:9,  gov:8,  target:10, dens:8,  clim:8, south:1, note:"The most underrated place on this map. Massive food surplus, ~95% renewable grid, stable, and of strategic interest to precisely nobody." },
  152: { n:"Chile",         iso:8,  food:8,  energy:7,  gov:7,  target:9,  dens:8,  clim:7, south:1, note:"Walled by the Atacama, the Andes and the Pacific — the best natural quarantine geography outside an island. The south is the good part." },
  32:  { n:"Argentina",     iso:6,  food:10, energy:7,  gov:5,  target:9,  dens:8,  clim:7, south:1, note:"Food and energy are abundant; the state is the weak link. Recurrent currency and governance crises are the failure mode, not invasion." },
  124: { n:"Canada",        iso:6,  food:9,  energy:9,  gov:9,  target:3,  dens:10, clim:5, note:"Hydro-rich, food-rich, empty. But it sits inside NORAD and downwind of the US — geographically attached to the primary target." },
  352: { n:"Iceland",       iso:10, food:3,  energy:10, gov:9,  target:7,  dens:10, clim:5, note:"Perfect energy — 100% renewable, geothermal heat straight out of the ground. Terrible food: imports most calories and cannot grow grain." },
  578: { n:"Norway",        iso:6,  food:4,  energy:10, gov:10, target:5,  dens:9,  clim:6, note:"Best-governed, best-powered country in Europe. Imports about half its food and shares a border with Russia." },
  372: { n:"Ireland",       iso:8,  food:9,  energy:4,  gov:8,  target:8,  dens:6,  clim:8, note:"Island, mild, and a huge net food exporter. Almost entirely dependent on imported fossil fuel — the grid is the hole." },
  756: { n:"Switzerland",   iso:3,  food:5,  energy:8,  gov:10, target:7,  dens:4,  clim:7, note:"The only country with fallout shelter capacity for its entire population and mandated national food reserves. Landlocked inside whatever Europe becomes." },
  246: { n:"Finland",       iso:5,  food:7,  energy:7,  gov:10, target:4,  dens:9,  clim:5, note:"Takes preparedness seriously — grain reserves, shelters, conscription. Also shares 1,340 km of border with Russia." },
  752: { n:"Sweden",        iso:5,  food:6,  energy:9,  gov:9,  target:6,  dens:8,  clim:6, note:"Hydro and nuclear, competent state, low density north of Stockholm. NATO membership raises its profile." },
  578.1:null,
  208: { n:"Denmark",       iso:5,  food:9,  energy:6,  gov:9,  target:6,  dens:4,  clim:7, note:"Large agricultural surplus per capita and serious wind capacity, but flat, small and easily reached." },
  600: { n:"Paraguay",      iso:4,  food:9,  energy:10, gov:4,  target:10, dens:8,  clim:6, south:1, note:"Itaipú gives it more hydroelectricity per person than almost anywhere on earth, plus a food surplus. Weak institutions are the constraint." },
  76:  { n:"Brazil",        iso:5,  food:10, energy:8,  gov:5,  target:7,  dens:7,  clim:6, south:1, note:"Agricultural superpower on a largely hydro grid. Governance and urban violence are the risk, not external attack." },
  188: { n:"Costa Rica",    iso:5,  food:6,  energy:9,  gov:8,  target:9,  dens:5,  clim:7, note:"Runs near-100% renewable electricity, abolished its army, stable. Small and food-import dependent for staples." },
  604: { n:"Peru",          iso:6,  food:6,  energy:6,  gov:4,  target:8,  dens:7,  clim:6, south:1, note:"Andean isolation is real protection. Political instability is chronic." },
  68:  { n:"Bolivia",       iso:6,  food:6,  energy:6,  gov:3,  target:9,  dens:8,  clim:6, south:1, note:"High, remote and irrelevant to any adversary. Fragile state, thin infrastructure." },
  170: { n:"Colombia",      iso:4,  food:7,  energy:7,  gov:4,  target:7,  dens:6,  clim:6, note:"Good agriculture and hydro; internal armed conflict remains the dominant risk." },
  484: { n:"Mexico",        iso:4,  food:5,  energy:5,  gov:4,  target:6,  dens:5,  clim:6, note:"Adjacent to the US in every sense — supply chains, migration pressure, and cartel control of territory." },
  840: { n:"United States", iso:5,  food:10, energy:8,  gov:6,  target:1,  dens:7,  clim:7, note:"Feeds itself many times over and generates its own power — and is the first target in every scenario on this list. Enormous internal variance: see the regional markers." },
  826: { n:"United Kingdom",iso:7,  food:5,  energy:4,  gov:7,  target:2,  dens:3,  clim:7, note:"Island geography helps against bio. Everything else works against it: import-dependent, dense, nuclear-armed, heavily targeted." },
  250: { n:"France",        iso:4,  food:8,  energy:8,  gov:7,  target:2,  dens:5,  clim:7, note:"Real food surplus and a nuclear grid that doesn't need fuel imports. Nuclear-armed, so a primary target." },
  276: { n:"Germany",       iso:3,  food:7,  energy:5,  gov:8,  target:3,  dens:3,  clim:7, note:"Competent and productive, but dense, energy-import dependent since 2022, and in the middle of the continent." },
  724: { n:"Spain",         iso:5,  food:8,  energy:6,  gov:7,  target:6,  dens:6,  clim:6, note:"Peninsular, agriculturally strong, decent renewables. Water stress is the long-term constraint." },
  620: { n:"Portugal",      iso:6,  food:5,  energy:7,  gov:7,  target:7,  dens:5,  clim:7, note:"Europe's western edge — the last place anything reaches. Doesn't grow enough of its own food." },
  40:  { n:"Austria",       iso:3,  food:6,  energy:8,  gov:8,  target:7,  dens:5,  clim:7, note:"Alpine hydro and a neutral posture. Landlocked with the same encirclement problem as Switzerland." },
  528: { n:"Netherlands",   iso:3,  food:7,  energy:4,  gov:8,  target:3,  dens:1,  clim:7, note:"Astonishing agricultural output — on imported energy and fertilizer, at the highest density in Europe, below sea level." },
  56:  { n:"Belgium",       iso:2,  food:5,  energy:5,  gov:7,  target:2,  dens:1,  clim:7, note:"NATO and EU headquarters, dense, import-dependent. Structurally poor position." },
  380: { n:"Italy",         iso:4,  food:6,  energy:4,  gov:6,  target:4,  dens:3,  clim:6, note:"Hosts US nuclear weapons, imports most of its energy, dense in the productive north." },
  616: { n:"Poland",        iso:2,  food:8,  energy:5,  gov:6,  target:3,  dens:4,  clim:6, note:"Strong agriculture, but the front line of any European conflict and coal-dependent." },
  804: { n:"Ukraine",       iso:2,  food:10, energy:4,  gov:3,  target:1,  dens:5,  clim:6, note:"One of the great breadbaskets on earth, and the live demonstration of what happens when drones and grid attacks meet a civilian population." },
  643: { n:"Russia",        iso:4,  food:9,  energy:10, gov:4,  target:1,  dens:9,  clim:4, note:"Self-sufficient in food and energy and enormous. Also the other pole of every nuclear scenario." },
  300: { n:"Greece",        iso:5,  food:6,  energy:5,  gov:6,  target:5,  dens:5,  clim:6, note:"Island dispersal is a genuine asset. Water and energy are not." },
  642: { n:"Romania",       iso:3,  food:8,  energy:6,  gov:5,  target:4,  dens:5,  clim:6, note:"Serious agricultural capacity and some domestic energy; NATO's Black Sea flank." },
  348: { n:"Hungary",       iso:2,  food:8,  energy:6,  gov:5,  target:5,  dens:4,  clim:7, note:"Food-secure and modestly off the target list; landlocked and institutionally contested." },
  203: { n:"Czechia",       iso:2,  food:6,  energy:6,  gov:7,  target:5,  dens:4,  clim:7, note:"Nuclear baseload and reasonable agriculture. Landlocked in central Europe." },
  703: { n:"Slovakia",      iso:2,  food:6,  energy:7,  gov:5,  target:5,  dens:5,  clim:7, note:"High nuclear share in the grid; small, landlocked, and politically volatile." },
  705: { n:"Slovenia",      iso:3,  food:5,  energy:7,  gov:7,  target:7,  dens:5,  clim:7, note:"Mountainous, small, low profile, decent hydro and nuclear mix." },
  191: { n:"Croatia",       iso:4,  food:6,  energy:6,  gov:6,  target:7,  dens:5,  clim:6, note:"Hydro-heavy grid and a fragmented coastline that disperses population." },
  688: { n:"Serbia",        iso:2,  food:8,  energy:5,  gov:4,  target:6,  dens:5,  clim:7, note:"Food-secure and non-aligned; regionally unstable." },
  100: { n:"Bulgaria",      iso:3,  food:7,  energy:6,  gov:5,  target:5,  dens:6,  clim:6, note:"Nuclear baseload and an agricultural base; depopulating and weakly governed." },
  233: { n:"Estonia",       iso:3,  food:7,  energy:5,  gov:8,  target:2,  dens:8,  clim:6, note:"Well-run and low-density, sitting directly on the Russian border." },
  428: { n:"Latvia",        iso:3,  food:7,  energy:6,  gov:7,  target:2,  dens:8,  clim:6, note:"Hydro on the Daugava and forest cover; same border problem." },
  440: { n:"Lithuania",     iso:3,  food:8,  energy:5,  gov:7,  target:2,  dens:7,  clim:6, note:"Agricultural surplus; wedged between Kaliningrad and Belarus." },
  112: { n:"Belarus",       iso:2,  food:8,  energy:4,  gov:3,  target:3,  dens:7,  clim:6, note:"Food-secure but a client state hosting Russian weapons." },
  792: { n:"Turkey",        iso:3,  food:8,  energy:5,  gov:5,  target:3,  dens:4,  clim:6, note:"Rare among large countries in near food self-sufficiency. Straddles every regional conflict and hosts US nuclear weapons." },
  392: { n:"Japan",         iso:8,  food:2,  energy:3,  gov:9,  target:3,  dens:2,  clim:7, note:"Superb state capacity and island isolation, undone by a 38% food self-sufficiency rate and almost total energy import dependence." },
  410: { n:"South Korea",   iso:4,  food:2,  energy:3,  gov:7,  target:1,  dens:1,  clim:6, note:"Dense, import-dependent, and within artillery range of the border. Structurally one of the worst positions on the map." },
  158: { n:"Taiwan",        iso:6,  food:2,  energy:2,  gov:7,  target:0,  dens:1,  clim:6, note:"The single most contested piece of territory on earth, with roughly a week of energy reserves." },
  156: { n:"China",         iso:4,  food:6,  energy:6,  gov:5,  target:1,  dens:5,  clim:6, note:"Vast interior and serious grain reserves, but a primary target and dependent on imported food and fuel at the margin." },
  356: { n:"India",         iso:4,  food:7,  energy:5,  gov:5,  target:2,  dens:2,  clim:4, note:"Feeds itself, barely, at extreme density. Nuclear-armed with two nuclear-armed neighbours and severe heat exposure." },
  496: { n:"Mongolia",      iso:6,  food:6,  energy:4,  gov:5,  target:8,  dens:10, clim:3, note:"Emptiest country on earth and strategically irrelevant. Brutal winters and thin infrastructure." },
  398: { n:"Kazakhstan",    iso:5,  food:8,  energy:8,  gov:4,  target:6,  dens:9,  clim:4, note:"Grain surplus, oil, uranium, and immense space. Authoritarian and landlocked between Russia and China." },
  360: { n:"Indonesia",     iso:6,  food:6,  energy:5,  gov:5,  target:6,  dens:4,  clim:6, note:"Archipelago dispersal is real protection against contagion; Java's density is not." },
  608: { n:"Philippines",   iso:6,  food:4,  energy:4,  gov:4,  target:4,  dens:3,  clim:6, note:"Island dispersal offset by typhoon exposure, food imports and a US basing agreement." },
  704: { n:"Vietnam",       iso:4,  food:8,  energy:5,  gov:5,  target:5,  dens:3,  clim:6, note:"Major rice exporter with a capable state; dense deltas and sea-level exposure." },
  764: { n:"Thailand",      iso:4,  food:9,  energy:5,  gov:5,  target:6,  dens:4,  clim:6, note:"One of the world's largest food exporters and not on anyone's target list." },
  458: { n:"Malaysia",      iso:5,  food:4,  energy:6,  gov:6,  target:6,  dens:5,  clim:6, note:"Energy-producing and stable, but imports much of its food." },
  702: { n:"Singapore",     iso:4,  food:0,  energy:2,  gov:9,  target:3,  dens:0,  clim:5, note:"Imports over 90% of food and much of its water. Best-run country here and among the least survivable." },
  586: { n:"Pakistan",      iso:3,  food:6,  energy:4,  gov:3,  target:1,  dens:3,  clim:3, note:"Nuclear-armed, water-stressed, politically fragile, extreme heat." },
  50:  { n:"Bangladesh",    iso:3,  food:5,  energy:3,  gov:4,  target:5,  dens:0,  clim:3, note:"Highest density of any large country, on a flood plain, with an import-dependent grid." },
  364: { n:"Iran",          iso:4,  food:5,  energy:7,  gov:3,  target:1,  dens:6,  clim:3, note:"Energy-rich, water-poor, and the subject of active military planning by several states." },
  682: { n:"Saudi Arabia",  iso:3,  food:1,  energy:7,  gov:5,  target:2,  dens:6,  clim:1, note:"Desalination is the entire water supply — it stops the moment the grid does. Food is almost entirely imported." },
  784: { n:"UAE",           iso:3,  food:1,  energy:7,  gov:6,  target:2,  dens:4,  clim:1, note:"Same desalination dependency, higher density, now a major AI datacenter hub and therefore a target." },
  376: { n:"Israel",        iso:3,  food:4,  energy:5,  gov:6,  target:0,  dens:2,  clim:3, note:"Under active missile and drone threat, water-engineered, nuclear-armed, small." },
  504: { n:"Morocco",       iso:5,  food:5,  energy:4,  gov:6,  target:6,  dens:5,  clim:4, note:"Stable by regional standards with growing solar; food and water are constrained." },
  818: { n:"Egypt",         iso:3,  food:3,  energy:5,  gov:4,  target:3,  dens:3,  clim:2, note:"The largest wheat importer on earth, with a population concentrated along a single river." },
  12:  { n:"Algeria",       iso:4,  food:3,  energy:7,  gov:4,  target:6,  dens:8,  clim:2, note:"Gas wealth and empty space; heavily food-import dependent." },
  710: { n:"South Africa",  iso:6,  food:7,  energy:4,  gov:4,  target:7,  dens:6,  clim:6, south:1, note:"Food-secure and far from every conflict — with a grid that already fails on its own, before anyone attacks it." },
  516: { n:"Namibia",       iso:7,  food:4,  energy:4,  gov:6,  target:9,  dens:10, clim:2, south:1, note:"Almost nobody lives there and nobody wants it. Almost nothing grows there either." },
  72:  { n:"Botswana",      iso:6,  food:3,  energy:4,  gov:7,  target:9,  dens:10, clim:2, south:1, note:"Africa's most stable democracy, empty and irrelevant to adversaries. The Kalahari sets the ceiling." },
  894: { n:"Zambia",        iso:5,  food:6,  energy:7,  gov:5,  target:9,  dens:8,  clim:5, south:1, note:"Hydro-powered, landlocked, peaceful, and arable. Drought now threatens the hydro." },
  716: { n:"Zimbabwe",      iso:5,  food:4,  energy:5,  gov:2,  target:9,  dens:7,  clim:5, south:1, note:"Good land and hydro access wasted by state collapse." },
  834: { n:"Tanzania",      iso:4,  food:5,  energy:5,  gov:5,  target:7,  dens:6,  clim:5, note:"Stable by regional standards with arable highlands and hydro potential." },
  404: { n:"Kenya",         iso:4,  food:5,  energy:6,  gov:5,  target:6,  dens:5,  clim:5, note:"Substantial geothermal in the Rift Valley — an unusual and underrated energy asset." },
  231: { n:"Ethiopia",      iso:5,  food:4,  energy:6,  gov:2,  target:6,  dens:4,  clim:5, note:"The GERD dam is a major power asset; recent internal conflict is the overriding risk." },
  566: { n:"Nigeria",       iso:4,  food:5,  energy:3,  gov:3,  target:5,  dens:3,  clim:4, note:"Grid failure is already the baseline condition; dense and food-stressed." },
  180: { n:"DR Congo",      iso:4,  food:5,  energy:6,  gov:1,  target:8,  dens:7,  clim:5, note:"Vast hydro potential and arable land inside one of the weakest states on earth." },
  450: { n:"Madagascar",    iso:8,  food:5,  energy:3,  gov:3,  target:9,  dens:6,  clim:6, south:1, note:"Genuine island isolation; very poor infrastructure and recurrent famine." },
  24:  { n:"Angola",        iso:5,  food:4,  energy:6,  gov:4,  target:8,  dens:8,  clim:5, south:1, note:"Hydro and oil, low density, off every target list; institutionally weak." },
  508: { n:"Mozambique",    iso:5,  food:5,  energy:6,  gov:3,  target:8,  dens:7,  clim:5, south:1, note:"Cahora Bassa hydro and arable land; insurgency in the north." },
  554.1:null,
  598: { n:"Papua New Guinea", iso:7, food:6, energy:4, gov:3, target:9, dens:8, clim:5, south:1, note:"Extreme terrain isolation and subsistence agriculture that never depended on the grid." },
  242: { n:"Fiji",          iso:9,  food:6,  energy:5,  gov:5,  target:9,  dens:6,  clim:7, south:1, note:"Remote Pacific island with local food production; tiny and supply-chain exposed." },
  64:  { n:"Bhutan",        iso:8,  food:6,  energy:10, gov:6,  target:9,  dens:8,  clim:5, note:"Exports hydroelectricity, mountain-isolated, deliberately disconnected. Wedged between India and China." },
  524: { n:"Nepal",         iso:7,  food:5,  energy:6,  gov:4,  target:8,  dens:3,  clim:4, note:"Himalayan isolation and hydro potential; poor and dense in the lowlands." },
  144: { n:"Sri Lanka",     iso:7,  food:5,  energy:4,  gov:4,  target:7,  dens:3,  clim:6, note:"Island isolation undercut by the 2022 demonstration of how fast import dependence becomes collapse." },
  328: { n:"Guyana",        iso:6,  food:7,  energy:5,  gov:4,  target:8,  dens:9,  clim:5, note:"Empty, arable and newly oil-rich — which has started to attract the wrong kind of attention." },
  740: { n:"Suriname",      iso:6,  food:7,  energy:6,  gov:4,  target:9,  dens:9,  clim:5, note:"Hydro-powered, nearly empty, and of no interest to anyone." },
  192: { n:"Cuba",          iso:8,  food:4,  energy:3,  gov:4,  target:6,  dens:4,  clim:7, note:"Learned forced agricultural self-sufficiency after 1991 — genuine institutional knowledge. The grid is failing now." },
  591: { n:"Panama",        iso:4,  food:4,  energy:7,  gov:6,  target:4,  dens:6,  clim:6, note:"The canal makes it strategically valuable, which is the opposite of what you want." },
  862: { n:"Venezuela",     iso:4,  food:3,  energy:5,  gov:1,  target:7,  dens:6,  clim:6, note:"Resource-rich and institutionally collapsed — the clearest proof that governance dominates endowment." },
  554.2:null,
  795: { n:"Turkmenistan",  iso:5,  food:5,  energy:8,  gov:3,  target:7,  dens:9,  clim:2, note:"Gas-rich, isolated, desert, and closed." },
  860: { n:"Uzbekistan",    iso:4,  food:6,  energy:6,  gov:4,  target:6,  dens:5,  clim:3, note:"Doubly landlocked with severe water constraints." },
  268: { n:"Georgia",       iso:4,  food:5,  energy:7,  gov:5,  target:4,  dens:6,  clim:6, note:"Mountain hydro and terrain; Russian troops already occupy part of it." },
  51:  { n:"Armenia",       iso:4,  food:5,  energy:6,  gov:5,  target:4,  dens:6,  clim:5, note:"Landlocked, blockaded on two sides, in an unresolved conflict." },
  4:   { n:"Afghanistan",   iso:6,  food:4,  energy:3,  gov:2,  target:6,  dens:5,  clim:3, note:"Terrain isolation is the only asset; everything else is absent." },
  104: { n:"Myanmar",       iso:5,  food:7,  energy:4,  gov:2,  target:6,  dens:5,  clim:5, note:"Rice surplus and hydro inside an active civil war." },
  116: { n:"Cambodia",      iso:4,  food:7,  energy:5,  gov:4,  target:7,  dens:5,  clim:6, note:"Rice surplus and the Tonlé Sap fishery; weak institutions." },
  418: { n:"Laos",          iso:5,  food:6,  energy:8,  gov:4,  target:8,  dens:7,  clim:6, note:"Exports hydroelectricity across Southeast Asia; mountainous and low-density." },
  408: { n:"North Korea",   iso:7,  food:3,  energy:3,  gov:3,  target:0,  dens:4,  clim:5, note:"Maximum isolation, minimum everything else, and first on the target list." },
  760: { n:"Syria",         iso:3,  food:4,  energy:3,  gov:1,  target:2,  dens:5,  clim:3, note:"" },
  368: { n:"Iraq",          iso:3,  food:3,  energy:6,  gov:2,  target:2,  dens:5,  clim:1, note:"" },
  887: { n:"Yemen",         iso:4,  food:2,  energy:2,  gov:1,  target:3,  dens:4,  clim:2, note:"" },
  729: { n:"Sudan",         iso:4,  food:4,  energy:3,  gov:1,  target:6,  dens:7,  clim:2, note:"" },
  706: { n:"Somalia",       iso:5,  food:3,  energy:2,  gov:1,  target:6,  dens:7,  clim:2, note:"" },
  434: { n:"Libya",         iso:4,  food:2,  energy:6,  gov:2,  target:6,  dens:9,  clim:1, note:"" },
  788: { n:"Tunisia",       iso:5,  food:4,  energy:4,  gov:5,  target:7,  dens:5,  clim:4, note:"" },
  466: { n:"Mali",          iso:4,  food:4,  energy:3,  gov:2,  target:7,  dens:7,  clim:2, note:"" },
  562: { n:"Niger",         iso:4,  food:3,  energy:3,  gov:2,  target:7,  dens:7,  clim:1, note:"" },
  148: { n:"Chad",          iso:4,  food:3,  energy:2,  gov:2,  target:7,  dens:7,  clim:1, note:"" },
  686: { n:"Senegal",       iso:4,  food:4,  energy:4,  gov:6,  target:7,  dens:4,  clim:4, note:"" },
  288: { n:"Ghana",         iso:4,  food:5,  energy:6,  gov:6,  target:7,  dens:4,  clim:5, note:"Akosombo hydro and relative stability." },
  384: { n:"Côte d'Ivoire", iso:4,  food:6,  energy:5,  gov:5,  target:7,  dens:4,  clim:5, note:"" },
  120: { n:"Cameroon",      iso:4,  food:5,  energy:5,  gov:3,  target:8,  dens:6,  clim:5, note:"" },
  800: { n:"Uganda",        iso:4,  food:5,  energy:6,  gov:4,  target:7,  dens:3,  clim:5, note:"" },
  646: { n:"Rwanda",        iso:4,  food:4,  energy:5,  gov:6,  target:8,  dens:2,  clim:6, note:"" },
  454: { n:"Malawi",        iso:4,  food:5,  energy:4,  gov:4,  target:9,  dens:3,  clim:5, note:"" },
  426: { n:"Lesotho",       iso:5,  food:3,  energy:7,  gov:5,  target:9,  dens:4,  clim:5, south:1, note:"Mountain kingdom with abundant water and hydro; entirely surrounded by South Africa." },
  516.1:null,
  340: { n:"Honduras",      iso:4,  food:5,  energy:6,  gov:3,  target:8,  dens:4,  clim:6, note:"" },
  320: { n:"Guatemala",     iso:4,  food:5,  energy:6,  gov:4,  target:8,  dens:3,  clim:6, note:"" },
  558: { n:"Nicaragua",     iso:4,  food:6,  energy:6,  gov:3,  target:8,  dens:6,  clim:6, note:"" },
  222: { n:"El Salvador",   iso:4,  food:4,  energy:6,  gov:5,  target:8,  dens:2,  clim:6, note:"" },
  214: { n:"Dominican Rep.",iso:7,  food:5,  energy:4,  gov:5,  target:8,  dens:3,  clim:6, note:"" },
  332: { n:"Haiti",         iso:7,  food:2,  energy:2,  gov:1,  target:8,  dens:2,  clim:6, note:"" },
  388: { n:"Jamaica",       iso:8,  food:4,  energy:3,  gov:6,  target:8,  dens:3,  clim:7, note:"" },
  152.1:null,
  248: null,
  304: { n:"Greenland",     iso:10, food:2,  energy:7,  gov:7,  target:5,  dens:10, clim:2, note:"Maximum isolation and hydro potential. Almost nothing grows, and its Arctic position is becoming strategically contested." },
  584: null, 583: null, 585: null,
  626: { n:"Timor-Leste",   iso:7,  food:4,  energy:3,  gov:4,  target:9,  dens:6,  clim:6, south:1, note:"" },
  548: { n:"Vanuatu",       iso:9,  food:6,  energy:5,  gov:5,  target:9,  dens:8,  clim:7, south:1, note:"Remote, subsistence-capable, cyclone-exposed." },
  90:  { n:"Solomon Is.",   iso:9,  food:6,  energy:4,  gov:3,  target:8,  dens:8,  clim:6, south:1, note:"" },
  776: { n:"Tonga",         iso:9,  food:5,  energy:4,  gov:5,  target:9,  dens:5,  clim:7, south:1, note:"" },
  882: { n:"Samoa",         iso:9,  food:6,  energy:5,  gov:6,  target:9,  dens:5,  clim:7, south:1, note:"" },
  270: null, 226: { n:"Eq. Guinea", iso:5, food:3, energy:6, gov:2, target:8, dens:7, clim:5, note:"" },
  178: { n:"Congo",         iso:4,  food:4,  energy:5,  gov:3,  target:8,  dens:9,  clim:5, note:"" },
  204: { n:"Benin",         iso:4,  food:5,  energy:4,  gov:5,  target:8,  dens:4,  clim:5, note:"" },
  768: { n:"Togo",          iso:4,  food:5,  energy:4,  gov:4,  target:8,  dens:4,  clim:5, note:"" },
  854: { n:"Burkina Faso",  iso:3,  food:4,  energy:3,  gov:2,  target:7,  dens:5,  clim:2, note:"" },
  324: { n:"Guinea",        iso:4,  food:5,  energy:6,  gov:3,  target:8,  dens:5,  clim:5, note:"" },
  694: { n:"Sierra Leone",  iso:5,  food:4,  energy:4,  gov:4,  target:8,  dens:4,  clim:5, note:"" },
  430: { n:"Liberia",       iso:5,  food:4,  energy:4,  gov:4,  target:8,  dens:5,  clim:5, note:"" },
  478: { n:"Mauritania",    iso:5,  food:3,  energy:5,  gov:4,  target:8,  dens:9,  clim:1, note:"" },
  232: { n:"Eritrea",       iso:5,  food:3,  energy:3,  gov:2,  target:6,  dens:6,  clim:2, note:"" },
  262: { n:"Djibouti",      iso:4,  food:2,  energy:4,  gov:4,  target:3,  dens:6,  clim:1, note:"Hosts foreign military bases from several rival powers on a very small piece of land." },
  728: { n:"South Sudan",   iso:4,  food:4,  energy:3,  gov:1,  target:7,  dens:6,  clim:3, note:"" },
  108: { n:"Burundi",       iso:4,  food:4,  energy:4,  gov:3,  target:8,  dens:2,  clim:5, note:"" },
  132: null, 174: null, 480: { n:"Mauritius", iso:9, food:3, energy:4, gov:7, target:9, dens:1, clim:7, south:1, note:"" },
  748: { n:"Eswatini",      iso:5,  food:4,  energy:5,  gov:4,  target:9,  dens:4,  clim:5, south:1, note:"" },
  212: null, 662: null, 670: null, 780: null, 44: null, 28: null, 308: null, 52: null,
  84:  { n:"Belize",        iso:5,  food:6,  energy:6,  gov:5,  target:9,  dens:8,  clim:6, note:"" },
  740.1:null,
  242.1:null,
  876: null, 258: null, 316: null,

  218: { n:"Ecuador",       iso:6,  food:7,  energy:7,  gov:4,  target:8,  dens:5,  clim:6, note:"Hydro-dominant grid and year-round growing seasons in the sierra; institutionally shaky and now facing severe cartel violence." },
  266: { n:"Gabon",         iso:5,  food:4,  energy:6,  gov:4,  target:8,  dens:9,  clim:5, note:"Almost entirely forested with a tiny population and hydro capacity; imports most food." },
  140: { n:"Central African Rep.", iso:5, food:4, energy:3, gov:1, target:8, dens:8, clim:5, note:"" },
  422: { n:"Lebanon",       iso:3,  food:3,  energy:2,  gov:1,  target:2,  dens:2,  clim:4, note:"The grid collapsed before anyone attacked it; in an active conflict zone." },
  400: { n:"Jordan",        iso:3,  food:2,  energy:4,  gov:5,  target:4,  dens:5,  clim:2, note:"Among the most water-scarce countries on earth, importing nearly all food and fuel." },
  634: { n:"Qatar",         iso:3,  food:1,  energy:7,  gov:6,  target:2,  dens:4,  clim:1, note:"Desalination-dependent, food-importing, and hosts the largest US air base in the region." },
  414: { n:"Kuwait",        iso:3,  food:1,  energy:7,  gov:5,  target:2,  dens:3,  clim:1, note:"" },
  512: { n:"Oman",          iso:4,  food:2,  energy:7,  gov:6,  target:4,  dens:7,  clim:1, note:"" },
  762: { n:"Tajikistan",    iso:6,  food:4,  energy:8,  gov:3,  target:7,  dens:6,  clim:4, note:"Nurek and Rogun make it one of the most hydro-dependent grids on earth; mountain-isolated and poor." },
  417: { n:"Kyrgyzstan",    iso:6,  food:5,  energy:8,  gov:4,  target:7,  dens:7,  clim:4, note:"Mountain hydro and terrain isolation; landlocked and fragile." },
  498: { n:"Moldova",       iso:2,  food:8,  energy:3,  gov:4,  target:3,  dens:4,  clim:7, note:"Fertile and food-secure; energy-dependent on a hostile neighbour and adjacent to an active war." },
  8:   { n:"Albania",       iso:4,  food:5,  energy:8,  gov:5,  target:7,  dens:5,  clim:6, note:"Runs almost entirely on domestic hydro — unusual and genuinely valuable. Mountainous and off every target list." },
  442: { n:"Luxembourg",    iso:2,  food:3,  energy:3,  gov:8,  target:4,  dens:2,  clim:7, note:"" },
  31:  { n:"Azerbaijan",    iso:4,  food:5,  energy:8,  gov:4,  target:5,  dens:5,  clim:5, note:"" },
  96:  { n:"Brunei",        iso:5,  food:2,  energy:7,  gov:6,  target:7,  dens:6,  clim:6, note:"" },
  624: { n:"Guinea-Bissau", iso:5,  food:5,  energy:3,  gov:2,  target:9,  dens:6,  clim:5, note:"" },
  270: { n:"Gambia",        iso:4,  food:4,  energy:3,  gov:5,  target:9,  dens:3,  clim:4, note:"" },
  44:  { n:"Bahamas",       iso:8,  food:2,  energy:3,  gov:6,  target:7,  dens:6,  clim:6, note:"" },
  540: { n:"New Caledonia", iso:9,  food:4,  energy:5,  gov:6,  target:8,  dens:8,  clim:7, south:1, note:"" },
  238: { n:"Falkland Is.",  iso:10, food:6,  energy:6,  gov:7,  target:6,  dens:10, clim:4, south:1, note:"Extreme isolation and a tiny population, with a live sovereignty dispute and a British garrison." },
  732: { n:"W. Sahara",     iso:5,  food:2,  energy:4,  gov:2,  target:7,  dens:10, clim:1, note:"" },
  630: { n:"Puerto Rico",   iso:7,  food:2,  energy:3,  gov:4,  target:5,  dens:2,  clim:6, note:"Hurricane Maria already demonstrated how long the grid stays down; imports ~85% of food." },
  196: { n:"Cyprus",        iso:6,  food:3,  energy:3,  gov:5,  target:5,  dens:4,  clim:4, note:"" },
  807: { n:"North Macedonia", iso:3, food:6, energy:5, gov:4, target:7, dens:5, clim:6, note:"" },
  70:  { n:"Bosnia & Herz.",iso:3,  food:5,  energy:7,  gov:3,  target:7,  dens:5,  clim:6, note:"Mountain hydro and terrain; unresolved internal political division." },
  499: { n:"Montenegro",    iso:4,  food:5,  energy:7,  gov:5,  target:7,  dens:6,  clim:6, note:"" },
  780: { n:"Trinidad & Tob.", iso:7, food:3, energy:7, gov:5, target:7, dens:2, clim:6, note:"" },
  52:  { n:"Barbados",      iso:8,  food:2,  energy:3,  gov:7,  target:8,  dens:1,  clim:6, note:"" },
  28:  { n:"Antigua & Barb.", iso:8, food:2, energy:3, gov:6, target:8, dens:2, clim:6, note:"" },
  308: { n:"Grenada",       iso:8,  food:3,  energy:3,  gov:6,  target:9,  dens:2,  clim:6, note:"" },
  212: { n:"Dominica",      iso:8,  food:5,  energy:6,  gov:6,  target:9,  dens:5,  clim:7, note:"Geothermal and hydro potential with a very small, rural population; hurricane-exposed." },
  662: { n:"St. Lucia",     iso:8,  food:3,  energy:3,  gov:6,  target:9,  dens:2,  clim:6, note:"" },
  670: { n:"St. Vin. & Gren.", iso:8, food:4, energy:4, gov:6, target:9, dens:2, clim:6, note:"" },
  132: { n:"Cabo Verde",    iso:8,  food:2,  energy:4,  gov:7,  target:8,  dens:3,  clim:3, note:"" },
  174: { n:"Comoros",       iso:8,  food:3,  energy:3,  gov:3,  target:9,  dens:2,  clim:6, south:1, note:"" },
  678: { n:"São Tomé",      iso:8,  food:4,  energy:3,  gov:5,  target:9,  dens:3,  clim:6, note:"" },
  248: { n:"Åland",         iso:8,  food:6,  energy:5,  gov:9,  target:7,  dens:8,  clim:6, note:"" },
  234: { n:"Faroe Is.",     iso:9,  food:5,  energy:6,  gov:8,  target:7,  dens:8,  clim:5, note:"" },
};
